# Generated by Django 5.2.2 on 2025-06-14 05:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Spinoff',
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, choices=[('food', '음식'), ('drink', '음료'), ('dessert', '디저트')], max_length=10, null=True),
        ),
    ]
