# Generated by Django 5.2.2 on 2025-06-14 05:40

import recipe_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_rename_ingredients_spinoff_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=recipe_app.models.category_image_upload_path),
        ),
    ]
