# Generated by Django 5.2.2 on 2025-06-14 05:49

import recipe_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0003_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinoff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=recipe_app.models.spinoff_image_upload_path),
        ),
    ]
